INFO 2024-06-13 00:31:45,903 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 00:32:15,612 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 00:32:38,237 views Starting list opportunity.
INFO 2024-06-13 00:32:38,253 basehttp "GET /opportunity HTTP/1.1" 200 5868
INFO 2024-06-13 00:32:39,625 views Starting list contacts.
INFO 2024-06-13 00:32:39,632 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-13 00:43:58,720 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 00:44:07,859 views Starting list contacts.
INFO 2024-06-13 00:44:07,879 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-13 00:44:09,819 views Starting list opportunity.
INFO 2024-06-13 00:44:09,826 basehttp "GET /opportunity HTTP/1.1" 200 5868
INFO 2024-06-13 00:44:11,000 views Starting add opportunity.
INFO 2024-06-13 00:44:11,002 views Init a new opportunity form.
INFO 2024-06-13 00:44:11,194 basehttp "GET /opportunity/add HTTP/1.1" 200 7927
INFO 2024-06-13 00:44:52,816 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-13 00:44:53,359 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 00:45:07,330 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-13 00:45:07,823 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 15:02:16,754 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 15:02:41,755 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-13 15:02:43,919 views Starting list contacts.
INFO 2024-06-13 15:02:43,972 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-13 15:02:46,466 views Starting edit contact: first last
INFO 2024-06-13 15:02:46,467 views Init edit ContactForm: first last
INFO 2024-06-13 15:02:46,581 basehttp "GET /contact/1/edit HTTP/1.1" 200 7278
INFO 2024-06-13 15:02:49,171 views Starting edit contact: first last
ERROR 2024-06-13 15:02:49,484 views Editing contact failed validation with error: * phone
  * Enter a valid phone number (e.g. (506) 234-5678) or a number with an international call prefix.
INFO 2024-06-13 15:02:49,497 basehttp "POST /contact/1/edit HTTP/1.1" 200 7495
INFO 2024-06-13 15:03:08,290 views Starting edit contact: first last
INFO 2024-06-13 15:03:08,301 views Editing contact pass validation
INFO 2024-06-13 15:03:08,318 basehttp "POST /contact/1/edit HTTP/1.1" 200 7524
INFO 2024-06-13 15:03:17,177 views Starting list contacts.
INFO 2024-06-13 15:03:17,184 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-13 15:03:19,026 views Starting add contact.
INFO 2024-06-13 15:03:19,027 views init a new ContactForm.
INFO 2024-06-13 15:03:19,058 basehttp "GET /contact/add HTTP/1.1" 200 7189
INFO 2024-06-13 15:03:40,503 views Starting add contact.
INFO 2024-06-13 15:03:40,506 views adding new contact passed validation.
INFO 2024-06-13 15:03:40,517 basehttp "POST /contact/add HTTP/1.1" 200 7430
INFO 2024-06-13 15:04:56,673 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 15:04:57,370 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 15:07:17,965 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 15:07:18,604 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:20:41,999 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:20:55,505 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-13 23:21:00,393 views Starting list opportunity.
INFO 2024-06-13 23:21:00,442 basehttp "GET /opportunity HTTP/1.1" 200 5868
INFO 2024-06-13 23:21:04,142 views Starting add opportunity.
INFO 2024-06-13 23:21:04,143 views Init a new opportunity form.
INFO 2024-06-13 23:21:04,352 basehttp "GET /opportunity/add HTTP/1.1" 200 7927
INFO 2024-06-13 23:21:42,446 views Starting add opportunity.
INFO 2024-06-13 23:21:42,450 views Adding a new opportunity passed validation.
INFO 2024-06-13 23:21:42,450 views <coroutine object OpportunityForm.to_dict at 0x000002F6502F6420>
INFO 2024-06-13 23:21:42,486 basehttp "POST /opportunity/add HTTP/1.1" 200 8175
INFO 2024-06-13 23:22:28,774 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-13 23:22:29,412 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:22:57,227 views Starting add opportunity.
INFO 2024-06-13 23:22:57,230 views Adding a new opportunity passed validation.
ERROR 2024-06-13 23:22:57,660 log Internal Server Error: /opportunity/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 90, in add_opportunity
    logger.info(await form.to_dict())
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py", line 32, in to_dict
    data['user'] = (await repos.get_user_by_id(data['user'])).to_dict()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_user_by_id() takes 0 positional arguments but 1 was given
ERROR 2024-06-13 23:22:57,685 basehttp "POST /opportunity/add HTTP/1.1" 500 84115
INFO 2024-06-13 23:24:10,215 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\repository\repositories.py changed, reloading.
INFO 2024-06-13 23:24:10,842 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:24:34,787 views Starting add opportunity.
INFO 2024-06-13 23:24:34,790 views Adding a new opportunity passed validation.
ERROR 2024-06-13 23:24:34,910 log Internal Server Error: /opportunity/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 90, in add_opportunity
    logger.info(await form.to_dict())
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py", line 32, in to_dict
    data['user'] = (await repos.get_user_by_id(data['user'])).to_dict()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\repository\repositories.py", line 97, in get_user_by_id
    return user_by_id[id]
           ~~~~~~~~~~^^^^
KeyError: '2'
ERROR 2024-06-13 23:24:34,924 basehttp "POST /opportunity/add HTTP/1.1" 500 87626
INFO 2024-06-13 23:29:25,597 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-13 23:29:26,545 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:29:52,148 views Starting add opportunity.
INFO 2024-06-13 23:29:52,150 views Adding a new opportunity passed validation.
ERROR 2024-06-13 23:29:52,265 log Internal Server Error: /opportunity/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 90, in add_opportunity
    logger.info(await form.to_dict())
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py", line 32, in to_dict
    data['user'] = (await repos.get_user_by_id(int(data['user']))).to_dict()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserDto' object has no attribute 'to_dict'
ERROR 2024-06-13 23:29:52,280 basehttp "POST /opportunity/add HTTP/1.1" 500 84199
INFO 2024-06-13 23:33:57,577 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:33:58,357 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:34:15,384 views Starting add opportunity.
INFO 2024-06-13 23:34:15,387 views Adding a new opportunity passed validation.
ERROR 2024-06-13 23:34:15,505 log Internal Server Error: /opportunity/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 90, in add_opportunity
    logger.info(await form.to_dict())
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py", line 38, in to_dict
    data['status'] = (await repos.get_opportunity_status_by_id(int(data['status']))).to_dict()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpportunityStatusDto' object has no attribute 'to_dict'. Did you mean: 'toDict'?
ERROR 2024-06-13 23:34:15,517 basehttp "POST /opportunity/add HTTP/1.1" 500 84457
INFO 2024-06-13 23:35:19,124 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:35:19,770 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:36:33,046 views Starting add opportunity.
INFO 2024-06-13 23:36:33,049 views Adding a new opportunity passed validation.
INFO 2024-06-13 23:36:33,050 views {'name': 'test', 'amount': Decimal('111'), 'user': {'id': 1, 'username': 'Test1'}, 'contact': {'last_name': 'last', 'first_name': 'first', 'email': 'asd@gmail.com', 'phone': '123-123-123', 'company': '123 ooo st', 'created_at': datetime.datetime(2024, 5, 21, 9, 0), 'updated_at': datetime.datetime(2024, 5, 21, 9, 0), 'id': 1}, 'status': {'id': 3, 'name': 'Delay'}}
INFO 2024-06-13 23:36:33,128 basehttp "POST /opportunity/add HTTP/1.1" 200 8175
INFO 2024-06-13 23:45:13,603 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:45:31,468 views Starting add opportunity.
INFO 2024-06-13 23:45:31,471 views Adding a new opportunity passed validation.
ERROR 2024-06-13 23:45:31,584 log Internal Server Error: /opportunity/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 90, in add_opportunity
    opportunity_dto = OpportunityDto(await form.to_dict(), id = -1, opened_at = datetime.now(), closed_at = datetime.now())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OpportunityDto.__init__() got multiple values for argument 'id'
ERROR 2024-06-13 23:45:31,595 basehttp "POST /opportunity/add HTTP/1.1" 500 80036
INFO 2024-06-13 23:46:22,313 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-13 23:46:22,932 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:46:40,542 views Starting add opportunity.
INFO 2024-06-13 23:46:40,545 views Adding a new opportunity passed validation.
ERROR 2024-06-13 23:46:40,675 log Internal Server Error: /opportunity/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 90, in add_opportunity
    opportunity_dto = OpportunityDto(await form.to_dict(), opened_at = datetime.now(), closed_at = datetime.now())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OpportunityDto.__init__() missing 5 required positional arguments: 'name', 'amount', 'user', 'contact', and 'status'
ERROR 2024-06-13 23:46:40,687 basehttp "POST /opportunity/add HTTP/1.1" 500 80372
INFO 2024-06-13 23:47:35,757 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-13 23:47:36,374 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:52:05,772 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:52:06,441 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:52:15,267 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:52:15,946 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:52:25,790 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:52:26,397 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:52:59,221 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:52:59,830 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:56:00,896 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:56:16,122 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:56:16,783 autoreload Watching for file changes with StatReloader
INFO 2024-06-13 23:56:40,152 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-13 23:56:40,917 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:01:53,146 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:05:49,799 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-14 00:05:50,586 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:06:29,883 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-14 00:06:30,651 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:09:47,519 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:10:24,783 views Starting add opportunity.
INFO 2024-06-14 00:10:24,785 views Adding a new opportunity passed validation.
ERROR 2024-06-14 00:10:24,901 log Internal Server Error: /opportunity/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 90, in add_opportunity
    opportunity_dto = OpportunityDto(**(await form.to_dict()), opened_at = datetime.now(), closed_at = datetime.now())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OpportunityDto.__init__() missing 1 required positional argument: 'id'
ERROR 2024-06-14 00:10:24,912 basehttp "POST /opportunity/add HTTP/1.1" 500 80043
INFO 2024-06-14 00:11:39,772 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-14 00:11:40,587 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:13:19,006 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-14 00:13:19,752 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:13:38,396 views Starting add opportunity.
INFO 2024-06-14 00:13:38,398 views Adding a new opportunity passed validation.
INFO 2024-06-14 00:13:38,400 views {'name': 'sss', 'amount': Decimal('22'), 'user': 2, 'contact': 1, 'status': 4, 'opened_at': datetime.datetime(2024, 6, 14, 0, 13, 38, 399857), 'closed_at': datetime.datetime(2024, 6, 14, 0, 13, 38, 399857), 'id': -1}
INFO 2024-06-14 00:13:38,474 basehttp "POST /opportunity/add HTTP/1.1" 200 8175
INFO 2024-06-14 00:17:35,067 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\models.py changed, reloading.
INFO 2024-06-14 00:17:35,839 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:18:35,092 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-14 00:18:35,714 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:18:57,242 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-14 00:18:57,848 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:19:42,344 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-14 00:19:42,990 autoreload Watching for file changes with StatReloader
INFO 2024-06-14 00:20:00,055 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-14 00:20:00,847 autoreload Watching for file changes with StatReloader
INFO 2024-06-15 01:48:00,651 autoreload Watching for file changes with StatReloader
ERROR 2024-06-15 01:48:02,355 log Internal Server Error: /task
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 60, in list_task
    return render(request, 'list-task.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'get_attr'
ERROR 2024-06-15 01:48:02,394 basehttp "GET /task HTTP/1.1" 500 241500
INFO 2024-06-15 01:48:36,587 basehttp "GET /task HTTP/1.1" 200 3847
INFO 2024-06-16 00:10:37,728 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:11:07,354 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-16 00:11:07,426 basehttp "GET /static/js/app.js HTTP/1.1" 304 0
INFO 2024-06-16 00:11:18,154 views Starting list tasks.
INFO 2024-06-16 00:11:18,178 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:17:11,483 views Starting list tasks.
INFO 2024-06-16 00:17:11,486 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:07,641 views Starting list tasks.
INFO 2024-06-16 00:19:07,646 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:09,206 views Starting list tasks.
INFO 2024-06-16 00:19:09,207 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:10,006 views Starting list tasks.
INFO 2024-06-16 00:19:10,010 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:32,660 views Starting list tasks.
INFO 2024-06-16 00:19:32,664 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:34,090 views Starting list tasks.
INFO 2024-06-16 00:19:34,093 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:34,791 views Starting list tasks.
INFO 2024-06-16 00:19:34,793 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:34,992 views Starting list tasks.
INFO 2024-06-16 00:19:34,997 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:35,274 views Starting list tasks.
INFO 2024-06-16 00:19:35,278 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:35,493 views Starting list tasks.
INFO 2024-06-16 00:19:35,497 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:19:46,992 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:19:53,551 views Starting list opportunity.
INFO 2024-06-16 00:19:53,612 basehttp "GET /opportunity HTTP/1.1" 200 5868
INFO 2024-06-16 00:19:54,757 views Starting list tasks.
INFO 2024-06-16 00:19:54,762 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:20:28,846 views Starting list tasks.
INFO 2024-06-16 00:20:28,848 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:22:53,500 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:22:58,292 views Starting list tasks.
INFO 2024-06-16 00:22:58,293 views 5
INFO 2024-06-16 00:22:58,310 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:23:10,119 views Starting list contacts.
INFO 2024-06-16 00:23:10,122 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-16 00:24:15,011 views Starting list tasks.
INFO 2024-06-16 00:24:15,012 views 5
INFO 2024-06-16 00:24:15,014 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:25:51,143 views Starting list tasks.
INFO 2024-06-16 00:25:51,143 views 5
INFO 2024-06-16 00:25:51,146 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:25:54,948 views Starting list tasks.
INFO 2024-06-16 00:25:54,949 views 5
INFO 2024-06-16 00:25:54,952 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:26:15,762 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:26:16,637 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:27:28,780 views Starting list tasks.
INFO 2024-06-16 00:27:28,794 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:29,659 views Starting list tasks.
INFO 2024-06-16 00:27:29,661 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:44,026 views Starting list tasks.
INFO 2024-06-16 00:27:44,032 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:46,120 views Starting list tasks.
INFO 2024-06-16 00:27:46,122 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:46,796 views Starting list tasks.
INFO 2024-06-16 00:27:46,797 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:47,181 views Starting list tasks.
INFO 2024-06-16 00:27:47,185 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:47,650 views Starting list tasks.
INFO 2024-06-16 00:27:47,654 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:48,723 views Starting list tasks.
INFO 2024-06-16 00:27:48,726 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:49,119 views Starting list tasks.
INFO 2024-06-16 00:27:49,125 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:49,463 views Starting list tasks.
INFO 2024-06-16 00:27:49,467 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:49,822 views Starting list tasks.
INFO 2024-06-16 00:27:49,825 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:50,467 views Starting list tasks.
INFO 2024-06-16 00:27:50,470 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:27:50,777 views Starting list tasks.
INFO 2024-06-16 00:27:50,782 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:28:49,968 views Starting list tasks.
INFO 2024-06-16 00:28:49,977 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:28:50,746 views Starting list tasks.
INFO 2024-06-16 00:28:50,751 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:28:50,909 views Starting list tasks.
INFO 2024-06-16 00:28:50,913 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:28:51,109 views Starting list tasks.
INFO 2024-06-16 00:28:51,112 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:28:51,323 views Starting list tasks.
INFO 2024-06-16 00:28:51,326 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:28:52,499 views Starting list tasks.
INFO 2024-06-16 00:28:52,502 basehttp "GET /task HTTP/1.1" 200 3324
INFO 2024-06-16 00:30:12,213 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:30:12,860 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:30:17,627 views Starting list tasks.
INFO 2024-06-16 00:30:17,643 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-16 00:39:14,499 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:39:15,095 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:39:22,993 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:39:23,708 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:39:35,711 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:39:36,299 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:40:16,412 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:40:17,179 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:41:38,708 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 00:41:39,274 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:43:41,997 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 00:43:42,567 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:44:50,129 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 00:44:50,707 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:45:17,323 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:45:17,914 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:45:24,755 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:45:25,432 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:45:39,149 views Starting add contact.
INFO 2024-06-16 00:45:39,150 views init a new ContactForm.
INFO 2024-06-16 00:45:39,288 basehttp "GET /task/add HTTP/1.1" 200 7189
INFO 2024-06-16 00:45:43,271 views Starting list tasks.
INFO 2024-06-16 00:45:43,284 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-16 00:45:44,846 views Starting add contact.
INFO 2024-06-16 00:45:44,847 views init a new ContactForm.
INFO 2024-06-16 00:45:44,859 basehttp "GET /task/add HTTP/1.1" 200 7189
INFO 2024-06-16 00:47:59,497 views Starting list tasks.
INFO 2024-06-16 00:47:59,503 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-16 00:48:00,831 views Starting add contact.
INFO 2024-06-16 00:48:00,832 views init a new ContactForm.
INFO 2024-06-16 00:48:00,839 basehttp "GET /task/add HTTP/1.1" 200 7189
INFO 2024-06-16 00:48:53,001 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-16 00:48:53,603 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:49:01,509 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-16 00:49:02,341 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:49:06,647 views Starting list tasks.
INFO 2024-06-16 00:49:06,660 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-16 00:49:07,798 basehttp "GET /task/add HTTP/1.1" 200 3847
INFO 2024-06-16 00:50:12,989 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:50:13,719 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:50:43,646 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:50:44,220 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:50:51,712 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:50:52,412 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:51:09,417 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 00:51:10,070 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:51:12,676 views Starting list opportunity.
INFO 2024-06-16 00:51:12,696 basehttp "GET /opportunity HTTP/1.1" 200 5868
INFO 2024-06-16 00:51:13,818 views Starting list tasks.
INFO 2024-06-16 00:51:13,824 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-16 00:51:14,895 views Starting add task.
INFO 2024-06-16 00:51:14,896 views Init a new task form.
ERROR 2024-06-16 00:51:15,135 log Internal Server Error: /task/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 146, in add_task
    await form.load()
          ^^^^^^^^^
AttributeError: 'TaskForm' object has no attribute 'load'
ERROR 2024-06-16 00:51:15,151 basehttp "GET /task/add HTTP/1.1" 500 78117
INFO 2024-06-16 00:52:41,685 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 00:52:42,270 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:54:49,752 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 00:54:50,644 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 00:54:53,444 views Starting add task.
INFO 2024-06-16 00:54:53,445 views Init a new task form.
INFO 2024-06-16 00:54:53,505 basehttp "GET /task/add HTTP/1.1" 200 7195
INFO 2024-06-16 00:59:35,476 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 00:59:36,662 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:05:58,533 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 01:05:59,201 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:06:03,022 views Starting list tasks.
INFO 2024-06-16 01:06:03,040 basehttp "GET /task HTTP/1.1" 200 5321
WARNING 2024-06-16 01:06:03,161 log Not Found: /favicon.ico
INFO 2024-06-16 01:06:03,163 basehttp - Broken pipe from ('127.0.0.1', 50075)
INFO 2024-06-16 01:06:04,228 views Starting add task.
INFO 2024-06-16 01:06:04,228 views Init a new task form.
INFO 2024-06-16 01:06:04,254 basehttp "GET /task/add HTTP/1.1" 200 7199
INFO 2024-06-16 01:07:47,589 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 01:07:48,227 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:08:57,544 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 01:08:58,126 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:09:05,731 views Starting add task.
INFO 2024-06-16 01:09:05,732 views Init a new task form.
INFO 2024-06-16 01:09:05,816 basehttp "GET /task/add HTTP/1.1" 200 7214
WARNING 2024-06-16 01:09:05,928 log Not Found: /favicon.ico
INFO 2024-06-16 01:09:05,930 basehttp - Broken pipe from ('127.0.0.1', 50126)
INFO 2024-06-16 01:16:06,749 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:16:11,220 views Starting add task.
INFO 2024-06-16 01:16:11,220 views Init a new task form.
INFO 2024-06-16 01:16:11,261 basehttp "GET /task/add HTTP/1.1" 200 7214
INFO 2024-06-16 01:16:11,448 basehttp - Broken pipe from ('127.0.0.1', 50248)
INFO 2024-06-16 01:18:05,726 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-16 01:18:06,320 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:19:31,477 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 01:19:32,059 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:20:35,116 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 01:20:35,776 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:22:14,413 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 01:22:15,056 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:24:03,340 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-16 01:24:03,929 autoreload Watching for file changes with StatReloader
INFO 2024-06-16 01:24:15,496 views Starting add task.
INFO 2024-06-16 01:24:15,497 views Init a new task form.
INFO 2024-06-16 01:24:15,568 basehttp "GET /task/add HTTP/1.1" 200 7992
INFO 2024-06-19 02:20:22,367 autoreload Watching for file changes with StatReloader
INFO 2024-06-19 02:20:28,825 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-19 02:20:29,090 basehttp - Broken pipe from ('127.0.0.1', 51682)
INFO 2024-06-19 02:20:31,510 views Starting list tasks.
INFO 2024-06-19 02:20:31,564 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-19 02:20:33,592 views Starting add task.
INFO 2024-06-19 02:20:33,593 views Init a new task form.
INFO 2024-06-19 02:20:33,781 basehttp "GET /task/add HTTP/1.1" 200 7992
WARNING 2024-06-19 02:20:34,085 log Not Found: /favicon.ico
INFO 2024-06-19 02:20:34,087 basehttp - Broken pipe from ('127.0.0.1', 51697)
INFO 2024-06-19 02:20:54,080 views Starting add task.
INFO 2024-06-19 02:20:54,223 views Adding a new task passed validation.
ERROR 2024-06-19 02:20:54,376 log Internal Server Error: /task/add
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 136, in add_task
    task_dto = TaskDto(**(await form.changed_data_to_dict()), id=-1, opened_at = datetime.now(), closed_at = datetime.now())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py", line 78, in changed_data_to_dict
    data['opportunity'] = (await repos.get_opportunity_by_id(data['opportunity'])).to_dict()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\repository\repositories.py", line 141, in get_opportunity_by_id
    return opportunity_by_id[id]
           ~~~~~~~~~~~~~~~~~^^^^
KeyError: '1'
ERROR 2024-06-19 02:20:54,402 basehttp "POST /task/add HTTP/1.1" 500 92202
INFO 2024-06-19 02:22:50,809 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\forms.py changed, reloading.
INFO 2024-06-19 02:22:51,580 autoreload Watching for file changes with StatReloader
