INFO 2024-06-26 02:00:59,275 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 02:01:19,364 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 02:01:19,711 basehttp - Broken pipe from ('127.0.0.1', 60945)
INFO 2024-06-26 02:05:18,711 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 02:05:42,581 autoreload Watching for file changes with StatReloader
ERROR 2024-06-26 02:05:50,874 log Internal Server Error: /contact
Traceback (most recent call last):
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\ms_identity_web\__init__.py", line 284, in assert_login
    if not self._adapter.identity_context_data.authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'identity_context_data'
ERROR 2024-06-26 02:05:58,474 basehttp "GET /contact HTTP/1.1" 500 72460
INFO 2024-06-26 02:06:32,608 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 02:06:51,699 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 12:21:26,349 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 12:24:27,392 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 12:26:31,774 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 12:27:14,834 autoreload C:\Users\lamma\working\repositories\CRM\crm\crm\settings.py changed, reloading.
INFO 2024-06-26 12:27:17,268 autoreload Watching for file changes with StatReloader
ERROR 2024-06-26 12:28:50,564 log Internal Server Error: /contact
Traceback (most recent call last):
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\ms_identity_web\__init__.py", line 285, in assert_login
    raise NotAuthenticatedError
ms_identity_web.errors.NotAuthenticatedError: 401 Unauthorized: User is not authenticated
ERROR 2024-06-26 12:28:55,805 basehttp "GET /contact HTTP/1.1" 500 72296
INFO 2024-06-26 12:30:46,299 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 12:30:58,410 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 12:31:35,405 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 12:35:12,038 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-26 12:35:19,997 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 12:35:24,170 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 12:35:39,917 autoreload C:\Users\lamma\working\repositories\CRM\crm\crm\settings.py changed, reloading.
INFO 2024-06-26 12:35:42,519 autoreload Watching for file changes with StatReloader
ERROR 2024-06-26 12:54:57,038 log Internal Server Error: /contact
Traceback (most recent call last):
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\ms_identity_web\__init__.py", line 284, in assert_login
    if not self._adapter.identity_context_data.authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'identity_context_data'
ERROR 2024-06-26 12:55:06,862 basehttp "GET /contact HTTP/1.1" 500 72460
ERROR 2024-06-26 12:57:29,725 log Internal Server Error: /contact
Traceback (most recent call last):
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lamma\working\Capstone Project\backend\email_classification_env\Lib\site-packages\ms_identity_web\__init__.py", line 284, in assert_login
    if not self._adapter.identity_context_data.authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'identity_context_data'
ERROR 2024-06-26 12:57:29,738 basehttp "GET /contact HTTP/1.1" 500 72460
INFO 2024-06-26 12:57:45,664 autoreload C:\Users\lamma\working\repositories\CRM\crm\crm\settings.py changed, reloading.
INFO 2024-06-26 12:57:48,440 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 12:57:53,108 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 12:58:44,758 autoreload C:\Users\lamma\working\repositories\CRM\crm\crm\settings.py changed, reloading.
INFO 2024-06-26 12:58:47,346 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 12:59:08,775 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-26 12:59:11,361 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:00:35,626 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-26 13:01:34,935 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:02:05,295 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:07:42,680 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 13:10:54,544 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-26 13:10:57,030 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:11:14,426 basehttp "GET /contact HTTP/1.1" 200 2671
INFO 2024-06-26 13:12:50,291 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-26 13:12:52,925 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:13:04,017 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 13:13:05,965 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 13:46:49,059 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:46:58,156 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 13:47:07,604 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 13:47:09,108 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 13:49:24,022 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 13:54:27,283 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:54:47,595 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 13:55:02,906 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 13:55:04,964 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 13:55:06,923 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 13:59:13,565 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 14:00:00,445 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 14:00:00,586 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
WARNING 2024-06-26 14:00:01,110 log Not Found: /favicon.ico
WARNING 2024-06-26 14:00:01,110 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-26 14:00:04,621 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 14:00:05,279 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 14:00:52,187 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 14:01:43,296 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 14:01:43,462 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
WARNING 2024-06-26 14:01:43,837 log Not Found: /favicon.ico
WARNING 2024-06-26 14:01:43,838 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-26 14:01:47,186 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 14:01:48,337 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 14:07:29,428 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 14:07:42,511 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 14:07:46,851 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 14:07:48,069 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 14:08:27,333 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 14:08:38,826 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 14:08:38,977 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
WARNING 2024-06-26 14:08:39,235 log Not Found: /favicon.ico
WARNING 2024-06-26 14:08:39,236 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-26 14:08:40,802 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 14:08:41,820 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
ERROR 2024-06-26 14:09:27,824 log Internal Server Error: /auth/redirect
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\ms_identity_web\django\msal_views_and_urls.py", line 41, in aad_redirect
    afterwards_go_to_url=reverse('index'))
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
ERROR 2024-06-26 14:09:27,830 basehttp "GET /auth/redirect?state=939bc2bd-c61e-47f8-a46a-ddf78bc93807&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..s53Zy8XDHypr4k8I.8qBHP2HS1r71Q98PTTJnHXlyOBLi7m4SMKHB95N2wjaASEMvtfwlcMo590Kn_Nl-0TsMCKY5dvu3ctZKF_rIfBLWDRnonHZw2NmX2JiaK8ek2TK0EStiYZo_cwIvp_s2eWzlUEVEMBsAmqrwxmezbFURcLofka_lOKUXzFbbJtRrxRrVmvoRR6lmywNtiNJ9b5HjBq_zsVK8kWVSfHQkFSO_MtIxKg334wU_IEUZNHhgDwukXlP0xdcZHQqDycsH19lGa66fv7lDkK_VmrSB8P0DnfkCJyAUpGGoy6q8AbeCclUtFawYVFdgWfz3M5ZTYO4S6oCUIyw7ar22kDRLE_YZNcIBdy-bpzGDe_z00mxXmuenfUDsTgxiSvT49wCDGK-ckJZuaiCUMMYxf5eHlz52FyKFZrYJ8hehuN4q0IaFERgQHcksH7KeMJmXAD_5Js5oXmGJZNoI7S10es_aso8BylM-Nj_15Tfm_eYbzcWLkjeMnKYI4T3i-xGipPbW5gcBFXzcHiga1v1epGIcRMdL3xJB9PB4YC7hT8wfB7F35yYQUNhOXExTIGaoPLoTn1OUNA.c4cmpQ9bD0TXfyb6xSTdNQ HTTP/1.1" 500 88922
ERROR 2024-06-26 14:16:31,208 log Internal Server Error: /auth/redirect
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\ms_identity_web\django\msal_views_and_urls.py", line 41, in aad_redirect
    afterwards_go_to_url=reverse('index'))
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
ERROR 2024-06-26 14:16:31,214 basehttp "GET /auth/redirect?state=939bc2bd-c61e-47f8-a46a-ddf78bc93807&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..XUJ0GRwl4aWj8LOj.OzhirqjssfUAnusOtLnWoKhnrG2brqIR_lE-6ZBAJ_885fML-ptU3YgVN5QVQSgQMaa5PRk2DPcrOuqUMDvq-OQLoGMZe6Bo4oYhlBlBG6J2VQtJvaAIfZrBZadp0_YjtPzvOUj2gCaqZ1CkU536To8bWRRagkpiXwNyBWRStfr2DrXtQOEkXzyb2r_7IlLBbBgMjUQwrGqpmx2l9grtjTfN0787vVWXUAoKhBSJ_Rh0s9sbR8gHhZ1QN8xRu0jB6PtK1yV6_oDM8GSjgzJt1qjDBR9FyAhbpUMZaBsfgmuApP4JbQeLDLWw7VX141ON9f0YG6c0GwolVAADHRojtrzB8CwY2U5V7-37nJHjq5SLEZS7_AbkQJAO6mKuiZyJTYyNaJRRp5vTMwx_NUx5XjBAtauLj2t8F3WTwcx2B0zIHU1OwhtNGMAOw3G3nMBNgJ_zrKUJglJPHQwqi52-aI3dI_rzzYQqTEi0KtSAMTqkkVnXj4S8nRrOtE26E73-PgzO9zXMvW75eXEVdq121aJ6qtx5dXnNxLaB1cKqY-a09RZ7e3HopzTJi8vLu72imdNMiQ.9GccEbX3Bw0nxttvSYqd9g HTTP/1.1" 500 88922
INFO 2024-06-26 14:16:45,776 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 14:17:25,509 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-26 14:17:25,619 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
WARNING 2024-06-26 14:17:26,024 log Not Found: /favicon.ico
WARNING 2024-06-26 14:17:26,025 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-26 14:17:33,188 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-26 14:17:34,303 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
ERROR 2024-06-26 14:17:51,553 log Internal Server Error: /auth/redirect
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\ms_identity_web\django\msal_views_and_urls.py", line 41, in aad_redirect
    afterwards_go_to_url=reverse('index'))
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
ERROR 2024-06-26 14:17:51,556 basehttp "GET /auth/redirect?state=a2f7d9ad-a80b-42e0-84c0-bd73cac499d6&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..E_fgu0qIiHVo2cSY.t3kEfYHjz19eLWmbTRLhhlCtSuEUcYtVxaSMroCq3QXKWCYROVGKlWQyzrpaH-WlL3TmyZkL35wy7icPCTPHKotLXY8baZPqE0-0JmLvTnqNtsa59mmaaLsqTDplNcVSApFg6O8ZBPcQPfigxH3B9tDVGg-yF2vOZcaT0I8ryFmKHzOEX8-LVOrRLmayhzlhq_PT9SiLTmdrNynT9BTWshWivRo-NOAH_ghidhz0jAPsj6wvUTE5ENH6iGCIu3yABTmo7KYVm7q-1vS2rsbD7nWJ7xyWZM6_ewf0NDEpG6JbxaMp9uyKji5jAMlemvSURxGy2tINpBksk1y8_wZXOE82BYqK1-uPmfdwDdad2VZtkXSdkievq1coEOO8khE7LHhOCoK2d-9uRsuC7Inn08DtW9QQLsexwJ_pnSw7Lmlr-gSR87JQ6nhUNTfbv4S1yDPnHlg1uJH08JXZimzrIDwvGQnwKXHM3--AkzNERDpuMzeN6EB40yuZgMhMJqK-vPxJkE_C0GJ5KLi8I4ODMjtcp_1N4QQKLBoPmlnrcUPK8dRUPE3o-wXjfVJ-CjuugY_W1g.g6rsa0uFJYDNxt_7UCTqRQ HTTP/1.1" 500 88878
WARNING 2024-06-26 14:17:51,599 log Not Found: /favicon.ico
WARNING 2024-06-26 14:17:51,600 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-26 16:36:06,057 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 16:36:09,587 basehttp "GET /auth/sign_out HTTP/1.1" 302 0
INFO 2024-06-26 16:36:09,740 basehttp "GET /auth/post_sign_out HTTP/1.1" 302 0
INFO 2024-06-26 16:36:09,741 basehttp "GET /index HTTP/1.1" 302 0
INFO 2024-06-26 16:36:10,561 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 16:36:17,844 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-26 16:36:18,250 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 16:36:31,142 basehttp "GET /auth/redirect?state=92295437-1f83-4805-be6c-de7666ffe7ba&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..7pxUJfrCJTLxQooq.Wu0sz-k8qmp153qNVrLPXRYGy3uSw6YOgoFsnsKvehzfp9QQyfqIqL7Y-nAWFty6CS-wMoj5Ugyt0QVkaAF-D0hOSP94JV9nh2bq6ofmrUtDIVyzqxDsGfWFJndXCGLer_Kx0Uzjj-6sOqmpvtIPdQ-eUnvBJTrkr2cE27MtadbhCq2jn8kagNgDmjIZXXmbnHiDCeC-O6ol7WtIedED2x5oH52A_BMlgN4rHhWZY2E43gMVBL980mx6V1uSTqU5IWULzp6cDLmC45PQMYv22C2h65sLIH2kpblpf0nqqPxo56e1Z5X1sNGc-WFmOXnPGUVHdNVqnD0nX4z1DMyHpDzTyChfJymlpgwKa7qk2Fzq8RBM0i0B4sAMyVeOlkdkSkpyrL4uFmFdMCqzsfEeRe0B72OVhuZzO8gijrE95YEnkDTY8mdPuMht990IJ9T6O1qtxWRa6lrMyt2rgP4-4ZKw7Vs81POHmAYrBNbwrj7fhN1mVWAZH1u_F-GLOcR2wNwP2AQdekT1fwAdm5dyCDd3st_fjb7qrtKTay21xDABE7hegShHhZHEQDlNsZvp2cv4qoeqEA.kAcMmnJh6Ca-Xkoiyhgykw HTTP/1.1" 302 0
INFO 2024-06-26 16:36:31,162 basehttp "GET /index HTTP/1.1" 200 2661
INFO 2024-06-26 16:36:31,332 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
WARNING 2024-06-26 16:36:31,716 log Not Found: /favicon.ico
WARNING 2024-06-26 16:36:31,718 basehttp "GET /favicon.ico HTTP/1.1" 404 4409
ERROR 2024-06-26 16:36:33,993 log Internal Server Error: /contact
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 337, in check_response
    raise ValueError(
ValueError: The view webapp.views.list_contact didn't return an HttpResponse object. It returned an unawaited coroutine instead. You may need to add an 'await' into your view.
ERROR 2024-06-26 16:36:33,996 basehttp "GET /contact HTTP/1.1" 500 73249
INFO 2024-06-26 16:38:57,558 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-26 16:38:58,256 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 16:39:05,202 views Starting list contacts.
INFO 2024-06-26 16:39:05,217 basehttp "GET /contact HTTP/1.1" 200 5653
WARNING 2024-06-26 16:39:05,262 log Not Found: /favicon.ico
WARNING 2024-06-26 16:39:05,263 basehttp "GET /favicon.ico HTTP/1.1" 404 4409
INFO 2024-06-26 16:39:07,381 views Starting list contacts.
INFO 2024-06-26 16:39:07,386 basehttp "GET /contact HTTP/1.1" 200 5653
WARNING 2024-06-26 16:39:07,427 log Not Found: /favicon.ico
WARNING 2024-06-26 16:39:07,428 basehttp "GET /favicon.ico HTTP/1.1" 404 4409
INFO 2024-06-26 16:39:08,860 views Starting list contacts.
INFO 2024-06-26 16:39:08,865 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-26 16:59:08,167 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 23:08:10,204 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 23:36:48,489 autoreload C:\Users\lamma\working\repositories\CRM\crm\crm\settings.py changed, reloading.
INFO 2024-06-26 23:36:49,159 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 23:37:03,609 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 23:38:59,791 autoreload Watching for file changes with StatReloader
ERROR 2024-06-26 23:39:06,138 basehttp "GET / HTTP/1.1" 500 59
ERROR 2024-06-26 23:39:06,182 basehttp "GET /favicon.ico HTTP/1.1" 500 59
INFO 2024-06-26 23:39:39,560 autoreload C:\Users\lamma\working\repositories\CRM\crm\crm\settings.py changed, reloading.
INFO 2024-06-26 23:39:40,173 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 23:58:41,042 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 23:58:55,117 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-26 23:58:55,840 autoreload Watching for file changes with StatReloader
INFO 2024-06-26 23:59:01,200 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-26 23:59:02,490 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-26 23:59:19,686 basehttp "GET /auth/redirect?state=2fa5081a-710d-425e-a0a2-2d29813eea9c&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..YDUf4XwNnEdvT7DI.gTs4WMlw1EqqLo5Uw6ACUVaDsZ8Ml1ONITCG6buSm7pOrGYb1iQj1gC-XnGQJ2l2Kh3p3wwXr6kOuzLA-cLpZCXoM95ICdDvTA-44-Fef1w-6LpYuHUecnCqtFQTCu7Scl0BSQLqmEX7BT8FuEonenPP5cdfaISCqGAlMN7l21l8U96nAQZsKBIppvuNLYsuU0Y3zm3zzfgPL9t5IxJ-ChH7MYLfGJ-2DWZmbU4li8rWzS_ipTFpPZsssgF3bNgKe7qsFpMat57il3qi1s4msmi7itASOaKOSvg0KDp8pB4orrIuYMarSRIn093iS5GCGSDhnsnJ3DjP8xHz2cjBhzzCdHK-VIe7OHX73JkG46lmo65O2q3HPOHczgwxss677gjjA5uglbvUyfrLbZZiIUvtR0H-oVd-8dD7iiDHHjkqVJgKaqx33VwjOHRSVOHRmNZ1LzSknRzX3_B8Z2A7yrFpiTaMsKq1JhNEF3Gf9cUrpXhdhEY54Q6T_N-jYojHhDxYmTuilYM68CUUS4wGYH2x-knV3eAgqQ5wvr3pw7Siy7DivqRVyGba8FeLDfe3wxfTCQw.7I_Dtd4W5nqRSXIICpokdw HTTP/1.1" 302 0
INFO 2024-06-26 23:59:19,717 basehttp "GET /index HTTP/1.1" 200 2661
INFO 2024-06-26 23:59:45,792 views Starting list contacts.
ERROR 2024-06-26 23:59:46,031 log Internal Server Error: /contact
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\ms_identity_web\__init__.py", line 290, in assert_login
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 25, in list_contact
    return render(request, 'list-contact.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'coroutine' object is not iterable
ERROR 2024-06-26 23:59:46,057 basehttp "GET /contact HTTP/1.1" 500 151791
INFO 2024-06-27 00:03:22,032 views Starting list tasks.
ERROR 2024-06-27 00:03:22,157 log Internal Server Error: /task
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py", line 128, in list_task
    return render(request, 'list-task.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'coroutine' object is not iterable
ERROR 2024-06-27 00:03:22,181 basehttp "GET /task HTTP/1.1" 500 146096
INFO 2024-06-27 00:07:20,175 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:07:32,704 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 00:07:34,653 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 00:07:50,161 basehttp "GET /auth/redirect?state=3da634dd-9bc0-4ee5-ad6e-eab6e7a46b22&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..Ovp0kfxEYZo7dAdw.5i2pi_TivYn3qdDlqIzR59w4sy1_pQXbjee1yRc7YoWk8W4CMVNxYMlijiprj25UwCGamKbmAq-i72pqAd6v1eEzdvAOmVSHqttMeu3a-QklX0rBQ6JaIlHW5jVxKtvyT8Uh9qs0k3m-c4F4RDy78zZ9Bks_ldGzRSeshnc4aG_cksCTAmOG9wrI8thwYKeUAAHNqt_-25tDIA0zOVNYoksFeNb4ZJ1Bi8g_iuaRqKRaBNqcyAKKXiAppsgjzvE8w10A5qH2LIEUOZl0_KQ5tMZBcOMR8Qz6xjWPiobuuNKeYMrIuoBeJrTPH0bCbqDyySPVfHbFiOczNHt9khpRrtJr2mwbOn2eW3rzHbRLjfGb3Tg6EEtNI8_t7OAZdxvrKTTaSlmAR3kJsx9i24OijB4PTOjXZXiZFAAIkISJtL3EgaiqIcDIqGNxN3GSu_J8vqAuQudx2HOQa1whJs4b3TSi9DC6x61y1smi4gRleJc-zpqXph5lygutCPmHf7sppEVUYISb07d6Qil2vzuD7-gQjaQQmb6hwCI0O3acObvbm2bQpXpRrzhXkpXt54U9fzw.EflqplleCn_Tc7hJfIdLdA HTTP/1.1" 302 0
INFO 2024-06-27 00:07:50,186 basehttp "GET /index HTTP/1.1" 200 2661
INFO 2024-06-27 00:07:50,496 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
WARNING 2024-06-27 00:07:51,708 log Not Found: /favicon.ico
WARNING 2024-06-27 00:07:51,709 basehttp "GET /favicon.ico HTTP/1.1" 404 4409
INFO 2024-06-27 00:07:53,511 views Starting list contacts.
INFO 2024-06-27 00:07:53,524 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-27 00:07:55,257 views Starting list tasks.
INFO 2024-06-27 00:07:55,266 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-27 00:07:56,898 views Starting list opportunity.
INFO 2024-06-27 00:07:56,906 basehttp "GET /opportunity HTTP/1.1" 200 5868
WARNING 2024-06-27 00:07:59,596 log Not Found: /dashboard
WARNING 2024-06-27 00:07:59,598 basehttp "GET /dashboard HTTP/1.1" 404 4403
INFO 2024-06-27 00:08:50,549 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-27 00:08:51,517 autoreload Watching for file changes with StatReloader
WARNING 2024-06-27 00:08:54,073 log Not Found: /favicon.ico
WARNING 2024-06-27 00:08:54,074 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-27 00:08:55,660 views Starting list contacts.
INFO 2024-06-27 00:08:55,675 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-27 00:08:56,598 views Starting list tasks.
INFO 2024-06-27 00:08:56,603 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-27 00:08:57,473 views Starting list opportunity.
INFO 2024-06-27 00:08:57,479 basehttp "GET /opportunity HTTP/1.1" 200 5868
WARNING 2024-06-27 00:08:58,720 log Not Found: /settings
WARNING 2024-06-27 00:08:58,722 basehttp "GET /settings HTTP/1.1" 404 4234
INFO 2024-06-27 00:09:03,721 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-27 00:34:35,284 autoreload Watching for file changes with StatReloader
ERROR 2024-06-27 00:34:49,121 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\ms_identity_web\__init__.py", line 285, in assert_login
    raise NotAuthenticatedError
ms_identity_web.errors.NotAuthenticatedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 199, in _get_response
    response = self.process_exception_by_middleware(e, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py", line 12, in process_exception
    return redirect('{}/{}}'.format(settings.AAD_CONFIG.django.auth_endpoints.prefix, settings.AAD_CONFIG.django.auth_endpoints.sign_in))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Single '}' encountered in format string
ERROR 2024-06-27 00:34:49,131 basehttp "GET / HTTP/1.1" 500 86252
WARNING 2024-06-27 00:34:49,210 log Not Found: /favicon.ico
WARNING 2024-06-27 00:34:49,211 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-27 00:35:34,634 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-27 00:35:35,419 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:35:53,680 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-27 00:35:54,381 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:35:57,998 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-27 00:35:59,052 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:36:05,828 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\middleware.py changed, reloading.
INFO 2024-06-27 00:36:06,487 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:36:15,301 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 00:36:16,012 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
ERROR 2024-06-27 00:36:28,994 log Internal Server Error: /auth/redirect
Traceback (most recent call last):
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\ms_identity_web\django\msal_views_and_urls.py", line 41, in aad_redirect
    afterwards_go_to_url=reverse('index'))
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lamma\working\repositories\CRM\venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
ERROR 2024-06-27 00:36:29,002 basehttp "GET /auth/redirect?state=3bcedf67-d39f-4a27-8dfe-566c9c916c41&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..KoYh0DeEaCWzm874.a_47Cdi7Mo6jDvkLUqgYRho-k9dnXQzQQlHCwi8RxPEItH4b3daMehuG-nur8u9NYhkRVv9vHw79Hz6WvuQTwX5UREc4WytbrOJ7TfjIGMZkpo3ewUhpV1yE72yjeqjiFEEs9hrLTV263sQ6IfKzvqUE2N6M5ytblaR8Z2qmXrl400UU2ynFf-UiVQ5nqUHfUPNrHUBxPdK5HUK5bIZuN_sGPjEm5WxAgYjym2RR6h5qqcSt4IxUkQOY_Gli4lQIJuWrqawSeXoC55M2a2yRLkLd9Jdnvv1efbV2Q2q-Fiqkj_CSksiGqgXcmt2nV1Olw6uRRtOiuV-_jespzvXWtWCM69I78uc3EiGtfgDpKJ-JDACEpo_IynPr09qeUi_2lIFpiHm0NyqjYQqpbuweuJge7VshEt4QT-vof5zbkdTXhlL03z0nNuNlnmQZc0Ul4a7Qr7GVrBdYjvOGsRGYuw56_3iZHupN_ccl6PQPyvwXF6AvT9ulj2646lySyKyBMHytsgstDnieX-QKsdQrcZ9BG8ICo7xyNHncJ0yScEZ12mY7vOHEoNokaPYdz_fCqI7-IdU.Aktysvt7TOzVQU4qjUb0QQ HTTP/1.1" 500 88886
WARNING 2024-06-27 00:36:29,097 log Not Found: /favicon.ico
WARNING 2024-06-27 00:36:29,099 basehttp "GET /favicon.ico HTTP/1.1" 404 4243
INFO 2024-06-27 00:37:38,654 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-27 00:37:39,309 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:38:03,985 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-27 00:38:04,588 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:38:09,639 basehttp "GET /auth/redirect?state=3bcedf67-d39f-4a27-8dfe-566c9c916c41&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..KoYh0DeEaCWzm874.a_47Cdi7Mo6jDvkLUqgYRho-k9dnXQzQQlHCwi8RxPEItH4b3daMehuG-nur8u9NYhkRVv9vHw79Hz6WvuQTwX5UREc4WytbrOJ7TfjIGMZkpo3ewUhpV1yE72yjeqjiFEEs9hrLTV263sQ6IfKzvqUE2N6M5ytblaR8Z2qmXrl400UU2ynFf-UiVQ5nqUHfUPNrHUBxPdK5HUK5bIZuN_sGPjEm5WxAgYjym2RR6h5qqcSt4IxUkQOY_Gli4lQIJuWrqawSeXoC55M2a2yRLkLd9Jdnvv1efbV2Q2q-Fiqkj_CSksiGqgXcmt2nV1Olw6uRRtOiuV-_jespzvXWtWCM69I78uc3EiGtfgDpKJ-JDACEpo_IynPr09qeUi_2lIFpiHm0NyqjYQqpbuweuJge7VshEt4QT-vof5zbkdTXhlL03z0nNuNlnmQZc0Ul4a7Qr7GVrBdYjvOGsRGYuw56_3iZHupN_ccl6PQPyvwXF6AvT9ulj2646lySyKyBMHytsgstDnieX-QKsdQrcZ9BG8ICo7xyNHncJ0yScEZ12mY7vOHEoNokaPYdz_fCqI7-IdU.Aktysvt7TOzVQU4qjUb0QQ HTTP/1.1" 302 0
INFO 2024-06-27 00:38:09,650 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-27 00:38:09,788 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
INFO 2024-06-27 00:38:22,647 views Starting list contacts.
INFO 2024-06-27 00:38:22,660 basehttp "GET /contact HTTP/1.1" 200 5653
WARNING 2024-06-27 00:38:24,184 log Not Found: /dashboard
WARNING 2024-06-27 00:38:24,185 basehttp "GET /dashboard HTTP/1.1" 404 4238
INFO 2024-06-27 00:38:45,287 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-27 00:38:45,977 autoreload Watching for file changes with StatReloader
WARNING 2024-06-27 00:38:48,038 log Not Found: /dashboard
WARNING 2024-06-27 00:38:48,040 basehttp "GET /dashboard HTTP/1.1" 404 4403
INFO 2024-06-27 00:39:02,537 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-27 00:39:03,135 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:39:14,012 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-27 00:39:14,618 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 00:39:22,759 basehttp "GET /dashboard HTTP/1.1" 200 2661
WARNING 2024-06-27 00:39:22,824 log Not Found: /favicon.ico
WARNING 2024-06-27 00:39:22,826 basehttp "GET /favicon.ico HTTP/1.1" 404 4418
INFO 2024-06-27 00:39:24,474 basehttp "GET /dashboard HTTP/1.1" 200 2661
INFO 2024-06-27 00:39:26,263 views Starting list contacts.
INFO 2024-06-27 00:39:26,270 basehttp "GET /contact HTTP/1.1" 200 5653
INFO 2024-06-27 00:39:27,307 views Starting list tasks.
INFO 2024-06-27 00:39:27,310 basehttp "GET /task HTTP/1.1" 200 5321
INFO 2024-06-27 00:39:29,065 views Starting list opportunity.
INFO 2024-06-27 00:39:29,068 basehttp "GET /opportunity HTTP/1.1" 200 5868
INFO 2024-06-27 00:39:30,868 basehttp "GET /dashboard HTTP/1.1" 200 2661
INFO 2024-06-27 00:40:49,001 basehttp "GET /auth/sign_out HTTP/1.1" 302 0
INFO 2024-06-27 00:40:50,007 basehttp "GET /auth/post_sign_out HTTP/1.1" 302 0
INFO 2024-06-27 00:40:50,012 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 00:40:52,471 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 00:41:01,634 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-27 00:41:01,959 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 00:41:13,723 basehttp "GET /auth/redirect?state=de733a6f-acc7-41ef-ba3a-56f0f8093bb1&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..ItbjQVOjODD2hPxC._XmVI7ijNzbf29D3ntRPsqrRjWv2Ph45iAoVFt_BeU0nhKDtx_NAUtglbw7Yb8ibBHiyUZwwN4wzt-5pzQaGe_z2CnO8k5ovXitU2nwjIvpr-3-9ZuP5Vin3pAUyyRYah_gPFZNKY7Nn0viAFWt83xRf8tpSPeSdMkH0JpUU5FGjaGRYORB7G-vBChUv1zPxzN_8mNZB666HOr7Pd0iLXoRqa62UD_Lgotf9-mse-YfjTgJ7EYwGn7Gs9w-Sp43dOnhkixcP_THFvlf3rA8WOXBlwuzAP4jL0wC9h7GVmhCaPEmm1aRlBnB4hgDIcfEThsh6IMoex3yfrhdwdJDrPOiw172gcSDoZZHHufeCaW9V1W5iM2cpptK7RcROiOMMcHENEP9VyG0iwpqllunqQTEIx0SjIURoeoRdd1w6SgiIEQJFbrg5UlppifTPB3KZaE2NP0dnqDKTBL30X0sdvLUuOCbVLfl2bngrINgNhzGp3VEkhZgwjpq4nwKxHSb9irrBlngkgjcv3f6d2-6ZsQqCqoHJUcEH2mLU6QxNsPXAGmolk8qQ2xdaUDZ5DcgKFQ.c64KlIXo-aUWsrqSrx7p0g HTTP/1.1" 302 0
INFO 2024-06-27 00:41:13,735 basehttp "GET / HTTP/1.1" 200 2661
WARNING 2024-06-27 00:41:13,829 log Not Found: /favicon.ico
WARNING 2024-06-27 00:41:13,831 basehttp "GET /favicon.ico HTTP/1.1" 404 4418
INFO 2024-06-27 01:26:53,533 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 01:27:24,066 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 01:27:27,781 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:27:29,773 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 01:27:44,542 basehttp "GET /auth/redirect?state=acea45e8-c908-4768-956d-d258f6f3cc3f&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..yZL6bL9jERr9SNWa.wU_cdcN0f3qNN5yXqoA0X1W5b-ttu57HXo6HXLmzQwH2P1kHa9k3NZklDG6GwjdfW2coF6O1RPf5DnpthTgoDekvJ3MtuQjEvqh3qNEZ68HHDtJw-EbBuekz0y0VdJs7xHVqKwvm2UyqMRAff02dbDBd0RJLC8FWPBhJH_tC-JuUpobjWKHYkJrMMB7BJPVTFbybECW5_poAiJ10lyWNizBj--zNTrqAIntRvMqWgT6nJ-x9UFKOJRVFnmtoiX6mxHibFwx2YG8pjY9-zZMPCUFDkwcgG5U-SvEkuTLV9yWKfMLjMZ_StTdwScHs10rUdZdKbGfhY5_UWmwnVYqXdLWAwVMS71Pk-LzvUm8Vz7F9jUI8YnKFSz6nwSEHmItjwJutFW-N3Z3nHxKY1SmHoRhQjUEkOrRkcxdIRt-rxNk_AQFEAMFpGKxpXzUGCqsriq9fxhwJ07ZlB_iCiURVZOhbHy8Y4blKVgmBcHDjFWoOIhWDx_yIkhMGUPoFNWhnrL4CeIWxd-fQuxFFySQ5nhbrt9tQOPtJiYqJV8H-WDH5ynQubp4JRIG9GvjCq-De7wn9.ZNzrMAriPO48wtk52dZOow HTTP/1.1" 302 0
INFO 2024-06-27 01:27:44,598 basehttp "GET / HTTP/1.1" 200 2661
INFO 2024-06-27 01:27:44,874 basehttp "GET /static/js/app.js HTTP/1.1" 200 130
WARNING 2024-06-27 01:27:46,521 log Not Found: /favicon.ico
WARNING 2024-06-27 01:27:46,522 basehttp "GET /favicon.ico HTTP/1.1" 404 4418
INFO 2024-06-27 01:28:04,322 basehttp "GET /auth/sign_out HTTP/1.1" 302 0
INFO 2024-06-27 01:28:04,712 basehttp "GET /auth/post_sign_out HTTP/1.1" 302 0
INFO 2024-06-27 01:28:04,717 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:28:05,064 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 01:28:14,198 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-27 01:28:15,619 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 01:28:29,501 basehttp "GET /auth/redirect?state=17293e7a-4926-45fe-9f42-5c0d7bf56380&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..aAGvzb9E1r7an8mi.k3JeQ2JVcReq4_MfROfLpdwVFxEaWAWdDju4uINGzCM2QNBzyOqrK3mr8UJZ8wqrJVr-daoTzX1g2a6N2n2EGQyXhPiYqob6HFQpr7qPB0aGs7b1Z6nApdVrcm34oH4GawLr92noOTn1prLTFuru3BxbaQC3unRjcU6prcVWgsSdLN5l28_yQqrqbX9kVkBvn_R4t_cnCLelwCvCIKV2felW_Qm6c2uNsA8mwe56fjXyZOjpqN3kph3fLC0pO5A_3btsnzlgEEK4EiJ4yyHEHeK5xZN0Vf8mZCA1QOR3_iIZy6zZwNrgSaTTMi-5-3emN6maQTMI9F4NeLyOes0UmenRuzKoDSRwdOGe8J2EqDLxvZ5BKr0BV3IqCtUtxCL_rnPifyQSR9Bdfd6KLoBGfifa-Rp8OvB4uxZPTE-29sWYB8JOd6cqTIjeVavc-cVPHHfzSVdtaIGil5htZi7WGMzuNHyz0M2QDEw_UScWu7z51rp7BC4Np_0tWwkPkt9XHFUKxt3m8xB6LHFSNVlz-RC_rj8lUUO_O7Aau4EmzSuEftfEXGOxFjyWZuJtMPxwIp2-0Q.RvOBzdN2_BWmAQNohgOltA HTTP/1.1" 302 0
INFO 2024-06-27 01:28:29,512 basehttp "GET / HTTP/1.1" 200 2661
WARNING 2024-06-27 01:28:29,621 log Not Found: /favicon.ico
WARNING 2024-06-27 01:28:29,623 basehttp "GET /favicon.ico HTTP/1.1" 404 4418
INFO 2024-06-27 01:30:19,648 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\views.py changed, reloading.
INFO 2024-06-27 01:30:20,408 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 01:30:46,024 basehttp "GET /auth/sign_out HTTP/1.1" 302 0
INFO 2024-06-27 01:30:47,723 basehttp "GET /auth/post_sign_out HTTP/1.1" 302 0
INFO 2024-06-27 01:30:47,728 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:30:49,528 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 01:31:04,498 autoreload C:\Users\lamma\working\repositories\CRM\crm\webapp\urls.py changed, reloading.
INFO 2024-06-27 01:31:05,111 autoreload Watching for file changes with StatReloader
INFO 2024-06-27 01:31:17,173 basehttp "GET /contact HTTP/1.1" 302 0
INFO 2024-06-27 01:31:19,725 basehttp "GET /auth/sign_in HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,686 basehttp "GET /auth/redirect?state=421f6ed4-fc4c-4056-956e-96e0068b6f59&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..7EB4InNBPTCVn31L.DeEHmCZuWk83vqJcmlcrmVNTWJUYATYVyez2yCZCLKEzjqec8YVyqqYWxJqr0drKrXZBXyOnbVfPmDZ_JO_iS0RzTxH_QiVEIqf7Fg0X6swLAk_hMgTjyoO8t-o11yolRcJzxJ_QMNtLf5JhyvjNwe8MdRaAB9Z-qbG1K1K-dbo_x-_416JTsyQpTmNy7EVKRL6Z2yQxBpy5X90SJY8bZGKPndngnMrNoD1VzC-k_IaQIPNeLV8FBGC6rc1jqEw6hW2FCZT9up9y_QZ5pO2wF5UkZbpAHaspxE0-fng4JD5t4cDUAMArLuRcO2F3ykNz44HORjWZIkbg816eK3k7Zl9gyLLon1-H45ofdP4EgbCsD_dcRUczXCru9z08nL7AFJXJDeHhgQcmQOk9aIjhFR7Bb4FQTkbE5CZXAwAkf4harO6lXtQ3Yv0VtQwSwgcxamKVAacatbEYedoDLdTBagZJpedBVNYqLTStkks8nL9uqTZAe4LYKIUusgtKxywhoDChKkNuUHDD9B4qVFDMvmO5KWUjw0rqmaNf57hURcF6XHArjEA9Sgqj9pvtRCcJu1eZuO0.QDE7v_qkrgL-CJ8LHXfvdw HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,696 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,704 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,714 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,721 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,732 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,740 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,746 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,755 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,765 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,774 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,784 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,795 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,803 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,812 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,823 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,834 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,844 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,853 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:32,861 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:42,986 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:42,993 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,002 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,010 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,019 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,030 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,039 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,048 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,057 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,067 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,076 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,084 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,093 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,101 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,108 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,118 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,126 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,135 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,143 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,150 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-06-27 01:31:43,159 basehttp "GET / HTTP/1.1" 302 0
